FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copiamos todo
COPY . .

# Publicamos específicamente la Web
RUN dotnet publish "CitasMedicas.Web/CitasMedicas.Web.csproj" -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .

# Asegúrate de que el nombre de la DLL sea el correcto
ENTRYPOINT ["dotnet", "CitasMedicas.Web.dll"]
